feat(val_preprocess): add preprocessing script
chime-experiment/bondia pull request #56
Opened 2020-10-21 21:12 UTC by nritsche

I would like to add this after the cron job running the daily pipeline.

2020-10-27 16:54 UTC, nritsche commented
Needs an sbatch script.

2021-03-25 17:06 UTC, nritsche commented
TODO
- [ ] make sure it's only ever queued once (possibly using ch_pipeline.processing.chp)
- [ ] check if there's anything to do before queuing.

2021-05-19 21:32 UTC, jrs65 requested changes

2021-05-19 21:32 UTC, jrs65 commented on scripts/val_preprocess.py
> +                    pol_sel=[0, 2],
I'm confused here. I think these need to take the `tryrun` argument or they will always end up doing the subsetting of the files even when `--tryrun` is set.

2021-05-19 21:32 UTC, jrs65 commented on scripts/val_preprocess.py
> +    "--tryrun/--notryrun",
I think a more typical name for this argument is `--dryrun` not `--tryrun`.

2021-05-19 21:32 UTC, jrs65 commented on scripts/val_preprocess.py
> +    lsd_from_filename = int(os.path.splitext(os.path.basename(in_file))[0][-4:])
If you're going to use `pathlib`, then you might as well be consistent and always use `pathlib` rather than mix in some `glob.glob` and `os.path` calls.

2021-05-19 21:32 UTC, jrs65 commented on scripts/val_preprocess.py
> +def run(tryrun):
I think the structure of this script quite confusing. You might consider separating it into two parts, one which finds the work that needs to be done, and one that takes that list and does it. Then your dryrun only need touch the first part. It could be a separate command to this script, rather than just an optional argument.

2021-06-14 16:03 UTC, jrs65 commented
@nritsche it doesn't seem like this requires that much to get it finished off and merged? What do you think?

2022-01-25 17:08 UTC, jrs65 approved these changes

2022-02-10 18:00 UTC, jrs65 approved these changes

2022-02-10 20:56 UTC, merged