Opinion buttons
chime-experiment/bondia pull request #58
Opened 2020-10-27 19:30 UTC by nritsche

2020-10-27 22:18 UTC, jrs65 requested changes

2020-10-27 22:18 UTC, jrs65 commented on bondia/opinion.py
> +        query.execute()
I would say it's cleaner to do:
```suggestion
        existing_decision.decision = decision
        existing_decision.save()
```

2020-10-27 22:18 UTC, jrs65 commented on bondia/opinion.py
> +                DataFlagOpinion.finish_time == lsd.end_time,
These comparisons seem very fragile to me. It would only require a very slight change to how the LSD gets calculated (which can happen when Skyfield updates the earth rotation parameters) for this not to work. The timestamps essentially have sub microsecond precision, which is far far beyond what we'd notice in CHIME anywhere else, but these comparisions would no longer work.

I guess because these are intended to parallel the DataFlag's closely, you can't have an LSD field and match very specifically on that, right?

2020-10-27 22:18 UTC, jrs65 commented on bondia/opinion.py
> +decision_options = ["good", "bad", "unsure"]
This should be defined in `chimedb.dataflag.orm`.

2020-10-28 00:23 UTC, nritsche commented on bondia/opinion.py
> +                DataFlagOpinion.finish_time == lsd.end_time,
The problem is rather that this table models a time period that isn't necessary a full LSD.
Even tough it seems like that might actually be more appropriate, I'm still not convinced, though. I would prefer to find a solution also working for flagging opinions for arbitrary time periods. How about we check here in the client (since I don't think peewee/mysql can do that) if the timestamps are (a few minutes?) close to each other?

2020-10-29 05:10 UTC, jrs65 approved these changes

2020-10-31 00:34 UTC, nritsche commented
Closes #13

2020-11-02 23:39 UTC, merged